resources:
  - name: messenger-app
    type: compute.v1.instance
    properties:
      zone: us-central1-a
      machineType: n1-standard-1
      disks:
        - initializeParams:
            diskSizeGb: '10'
            sourceImage: projects/debian-cloud/global/images/family/debian-11
      networkInterfaces:
        - name: global/networks/default
        - accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
              networkTier: PREMIUM
      metadata:
        items:
          - key: startup-script
            value: |
              #!/bin/bash
              sudo apt-get update
              sudo apt-get install -y git
              go get github.com/us190190/messenger
              cd $GOPATH/src/github.com/us190190/messenger
              go build
              ./messenger
